nombre=input('Cual es tu nombre: ')
print('Tu nombre es:', nombre)
print('')
grado=input('Cual es tu grado:')
print('Tu grado es:', grado)
print('')
grupo=input('En q grupo estas:')
print('Estas en el grupo:', grupo)
print('')
comidafav=input('Cual es tu comida favorita: ')
print('Tu comida favorita es:', comidafav)
print('')
mensaje=input('Un mensaje: ')
print('Mensaje:', mensaje)
print('')