nombre=input('Cual es tu nombre: ')
print('1:', nombre)
print('')
mensaje=input('Cual es tu edad: ')
print('2:', mensaje)
print('')
grado=input('En q pais vives:')
print('3:', grado)
print('')
grupo=input('Cual es tu comida favorita :')
print('4:', grupo)
print('')
comidafav=input('Que comida detestas: ')
print('5:', comidafav)
print('')
mensaje=input('Eres hombre o mujer: ')
print('6:', mensaje)
print('')
nombre=input('Que te da miedo: ')
print('7:', nombre)
print('')
grado=input('Que deporte te gusta:')
print('8:', grado)
print('')
grupo=input('A donde te gustaria viajar:')
print('9:', grupo)
print('')
comidafav=input('Que genero musical escuchas: ') 
print('10:', comidafav)
print('')
