b=int(input('ingresa base:'))
h=int(input('ingresa altura:'))
print('triangulo:',b*h/2)
print('')
l=int(input('ingresa longitud:'))
w=int(input('ingresa ancho:'))
print('rectangulo:',l*w)
print('')
l=int(input('ingresa lado:'))
ap=int(input('ingresa apotema:'))
print('pentagon:',l*5*ap/2)