name=input('What is your name:')
pro1=input('Product name:')
price1=int(input('Precio objeto:'))
pro2=input('Product name:')
price2=int(input('Precio objeto:'))
pro3=input('Product name:')
price3=int(input('Precio objeto:'))
pro4=input('Product name:')
price4=int(input('Precio objeto:'))
pro5=input('Product name:')
price5=int(input('Precio objeto:'))
print('')
print('TICKET')
print('Your name is:',name)
print('Your products are: ',pro1,pro2,pro3,pro4,pro5)
Suma=(price1+price2+price3+price4+price5)
print('Price without IVA: ',Suma)
Subtotal=((price1+price2+price3+price4+price5)*0.16)
print('IVA: ',Subtotal)
print('Your total price is: ',Suma+Subtotal)
